### ISSUE TITLE
docker build crashes my machine

### ISSUE THREAD

**Issue by dustyatx** [togethercomputer/stripedhyena#2]
Not sure if this is a problem with my machine or not but I have a 32 core machine i9 with 128 GB of RAM & this pegs all my cores at 100%. Looks like there is some substantial compiling going on. The second time it spikes up my machine crashes. I was trying to figure out how to limit the number of cores it uses.. not sure but it might also spike memory usage up to 128GB or that could be an artifact of HTOP being disconnected over a SSH session hard to say. 

Not my area of expertise but I haven't run into to many containers doing this kind of intensive build, normally it's just software installations and configuration.

I'm including the terminal logging that I captured. 
[dockerbuild_terminal_logging.txt](https://github.com/togethercomputer/stripedhyena/files/13643378/dockerbuild_terminal_logging.txt)

**Comment by dustyatx** [comment]
OK just confirmed that it also crashes on a Google Cloud VM, 22 Cores, 128GB of ram. Looks like this one ran out of RAM as well.. 
[gc_docker_build_fail_22core_128.txt](https://github.com/togethercomputer/stripedhyena/files/13651129/gc_docker_build_fail_22core_128.txt)
![Screenshot 2023-12-12 at 10 57 58 AM](https://github.com/togethercomputer/stripedhyena/assets/122811501/1c8c6f60-b2dd-4f59-9594-4e1b9e0dcef3)
![Screenshot 2023-12-12 at 10 59 16 AM](https://github.com/togethercomputer/stripedhyena/assets/122811501/8edc95db-e424-4f89-810a-911ea1374485)

**Comment by nedRad88** [comment]
Hi! I had the same issue. I changed the Dockerfile so to include the env variable MAX_JOBS:

RUN rm -rf ./flash-attention/* && \
    pip uninstall flash_attn -y && \
    git clone https://github.com/Dao-AILab/flash-attention.git && \
    cd flash-attention/csrc/rotary && MAX_JOBS=4 python setup.py install && \
    cd ../layer_norm && MAX_JOBS=4 python setup.py install && \
    cd ../../ && MAX_JOBS=4 python setup.py install

RUN MAX_JOBS=4 pip install ninja tokenizers==0.14.1 einops transformers==4.34.1

I used 4, but I guess you can go for something higher (maybe 10).

**Comment by dustyatx** [comment]
@nedRad88 AH thank you.!! It's been a long time since I worked with Docker. I was trying MAX_JOBS in with the docker build command and it wouldn't work. .

**Comment by orangetin** [comment]
Yes! @nedRad88 's suggestion should work 👍 . `ninja` can use a lot of resources when building flash-attn if MAX_JOBS is not specified. Feel free to re-open if the issue persists.

**Comment by dustyatx** [comment]
I'd recommend updating the documentation to explain this workaround. Otherwise others might not think to check this thread.

**Comment by dustyatx** [comment]
@nedRad88 & @orangetin 

This work around did not work for me. I updated the Docker file with the MAX_JOBS set to 4 and I'm still running out of memory. 

`FROM nvcr.io/nvidia/pytorch:23.06-py3

WORKDIR /workdir

RUN rm -rf ./flash-attention/* && \
    pip uninstall flash_attn -y && \
    git clone https://github.com/Dao-AILab/flash-attention.git && \
    cd flash-attention/csrc/rotary && MAX_JOBS=4 python setup.py install && \
    cd ../layer_norm && python setup.py install && \
    cd ../../ && python setup.py install


RUN MAX_JOBS=4 pip install ninja tokenizers==0.14.1 einops transformers==4.34.1`

**Comment by dustyatx** [comment]
OK I got it to build.. had to rent a VM big enough to handle this.. for some reason the max_jobs setting didn't seem to do anything for me. 

96 Core & 604 GB (300+ used at peak).

**Comment by Zymrael** [comment]
`MAX JOBS` controls how many processes to launch in parallel for compilation. You could try adding that as env variable or setting that for each `flash_attn` install step e.g.,
```
cd flash-attention/csrc/rotary && MAX_JOBS=4 python setup.py install &&
cd ../layer_norm && MAX_JOBS=4 python setup.py install &&
cd ../../ && MAX_JOBS=4 python setup.py install
```
